version: '3'

services:
  mariadb:
    image: mariadb
    volumes:
      - db:/var/lib/mysql/data/
    networks: 
      - wordpress
    environment:
      - MYSQL_ROOT_PASSWORD=albert

  wordpress:
    image: wordpress
    networks: 
      - wordpress
    depends_on:
      - mariadb
    ports:
      - "80:80"

volumes:
  db:

networks:
  wordpress: